#!/usr/bin/env node
// Same-category pairwise Jaccard overlap of the BUILT PDPs' visible text.
//
// WHY THIS IS A COMMITTED SCRIPT AND NOT AN AD-HOC MEASUREMENT. On 2026-10-03
// a distinctness audit was asked to reproduce a baseline of "0.48 RAM / 0.39
// SSD" recorded from 2026-09-25. The method behind those two numbers was
// written down nowhere: not in CLAUDE.md, not in scripts/, not in docs/. Four
// defensible methods on the same pages that day produced means between 0.435
// and 0.745, so the old figures could not be compared to anything. A number
// whose method is not recorded is not a baseline, it is an anecdote, and this
// file exists so the next measurement is the same code rather than the same
// intention.
//
// THE METHOD, fixed:
//   1. read every built PDP carrying the generator marker
//   2. take <main> only, so nav, header and footer boilerplate cannot inflate
//      the overlap (measured: including them moves RAM 0.560 to 0.588)
//   3. strip <script>, <style> and comments; replace tags with spaces; decode
//      nothing, drop entities to spaces; lowercase
//   4. tokenise on /[a-z0-9][a-z0-9.$/%-]*/g, which keeps "32gb", "$18.44",
//      "6000mhz" and "cl30" whole, because the digits ARE the distinctness
//   5. SET per page (not a bag), then Jaccard over every unordered pair within
//      a category
//
// BIGRAM SHINGLES ARE THE HEADLINE METRIC. Unigram sets reward a page merely
// for mentioning different numbers; shingles measure whether the SENTENCES
// differ, which is what the August 2026 spam update was about. Both are
// printed, because the unigram figure is the one that moves when values are
// interpolated into fixed prose and the shingle figure is the one that moves
// when the prose itself changes.
const fs = require('fs');
const path = require('path');

const FRONTEND = path.join(__dirname, '..', 'frontend');
const MARKER = '<!-- generated by generate-product-pages.js -->';
const TOKEN = /[a-z0-9][a-z0-9.$/%-]*/g;

function visibleMain(html) {
  const m = /<main[^>]*>([\s\S]*?)<\/main>/.exec(html);
  let body = m ? m[1] : html;
  body = body.replace(/<script[\s\S]*?<\/script>/g, '');
  body = body.replace(/<style[\s\S]*?<\/style>/g, '');
  body = body.replace(/<!--[\s\S]*?-->/g, '');
  body = body.replace(/<[^>]+>/g, ' ');
  body = body.replace(/&[a-z]+;|&#\d+;/g, ' ');
  return body.toLowerCase();
}

function tokens(text, bigram) {
  const w = text.match(TOKEN) || [];
  if (!bigram) return new Set(w);
  const out = new Set();
  for (let i = 0; i < w.length - 1; i++) out.add(w[i] + '_' + w[i + 1]);
  return out;
}

function jaccard(a, b) {
  if (!a.size || !b.size) return 0;
  let inter = 0;
  const [small, large] = a.size <= b.size ? [a, b] : [b, a];
  for (const t of small) if (large.has(t)) inter++;
  return inter / (a.size + b.size - inter);
}

function pagesFor(category) {
  const dir = path.join(FRONTEND, category);
  const out = [];
  for (const slug of fs.readdirSync(dir)) {
    const f = path.join(dir, slug, 'index.html');
    let html;
    try { html = fs.readFileSync(f, 'utf8'); } catch (_) { continue; }
    if (!html.includes(MARKER)) continue;   // listing page, template, anything hand-written
    out.push({ slug, text: visibleMain(html) });
  }
  return out.sort((a, b) => (a.slug < b.slug ? -1 : 1));
}

function percentile(sorted, p) {
  const k = (sorted.length - 1) * (p / 100);
  const lo = Math.floor(k), hi = Math.min(lo + 1, sorted.length - 1);
  return sorted[lo] + (sorted[hi] - sorted[lo]) * (k - lo);
}

function stats(vals) {
  const s = [...vals].sort((a, b) => a - b);
  return {
    n: s.length,
    mean: s.reduce((t, v) => t + v, 0) / s.length,
    median: percentile(s, 50),
    p90: percentile(s, 90),
    min: s[0],
    max: s[s.length - 1],
  };
}

function run() {
  const f3 = (v) => v.toFixed(3);
  console.log('Pairwise Jaccard on built PDP <main> text. Shingles are the headline metric.');
  console.log('');
  console.log(['category', 'metric', 'pages', 'pairs', 'mean', 'median', 'p90', 'min', 'max'].join('\t'));
  const summary = {};
  for (const category of ['ram', 'ssd']) {
    const pages = pagesFor(category);
    for (const [label, bigram] of [['unigram', false], ['shingle', true]]) {
      const sets = pages.map((p) => tokens(p.text, bigram));
      const vals = [];
      for (let i = 0; i < sets.length; i++) {
        for (let j = i + 1; j < sets.length; j++) vals.push(jaccard(sets[i], sets[j]));
      }
      const s = stats(vals);
      summary[category + '/' + label] = s;
      console.log([category, label, pages.length, s.n, f3(s.mean), f3(s.median), f3(s.p90), f3(s.min), f3(s.max)].join('\t'));
    }
  }
  return summary;
}

if (require.main === module) run();
module.exports = { visibleMain, tokens, jaccard, pagesFor, run };
